[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sensor_pipeline"
version = "1.0.0"

description = "Sensor pipeline"
requires-python = ">=3.11"
license = {text = "Proprietary License"}
classifiers = [
    "License :: Proprietary License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "PyYaml==6.0.2",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "pytest",
    "pyhamcrest",
]

[project.scripts]
sensor_pipeline = "sensor_pipeline.main:main"

[black]
line_length = 120
